version: '3.8'

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./.docker-volume-mnt/postgres_data
      o: bind

services:
  postgres:
    container_name: postgres-dev
    restart: always
    image: postgres:16
    networks:
      - transcendence
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    container_name: django-dev
    restart: always
    build: .
    networks:
      - transcendence
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/home:delegated

# Only for Dev:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    networks:
      - transcendence
    ports:
      - 9001:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev