global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django'
    static_configs:
      - targets: ['django-dev:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
