http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://${ELASTIC_HOST}:${ELASTIC_PORT}" ]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "${ELASTIC_PASSWORD}"